// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/order/v1/order.proto

package orderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderItemProto carries a line item for GetOrder callers.
type OrderItemProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItemId    string                 `protobuf:"bytes,1,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	NameSnapshot  string                 `protobuf:"bytes,2,opt,name=name_snapshot,json=nameSnapshot,proto3" json:"name_snapshot,omitempty"`
	PriceSnapshot int64                  `protobuf:"varint,3,opt,name=price_snapshot,json=priceSnapshot,proto3" json:"price_snapshot,omitempty"`
	Qty           int32                  `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	CutoffId      string                 `protobuf:"bytes,5,opt,name=cutoff_id,json=cutoffId,proto3" json:"cutoff_id,omitempty"`
	Date          string                 `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemProto) Reset() {
	*x = OrderItemProto{}
	mi := &file_proto_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemProto) ProtoMessage() {}

func (x *OrderItemProto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemProto.ProtoReflect.Descriptor instead.
func (*OrderItemProto) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItemProto) GetMenuItemId() string {
	if x != nil {
		return x.MenuItemId
	}
	return ""
}

func (x *OrderItemProto) GetNameSnapshot() string {
	if x != nil {
		return x.NameSnapshot
	}
	return ""
}

func (x *OrderItemProto) GetPriceSnapshot() int64 {
	if x != nil {
		return x.PriceSnapshot
	}
	return 0
}

func (x *OrderItemProto) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *OrderItemProto) GetCutoffId() string {
	if x != nil {
		return x.CutoffId
	}
	return ""
}

func (x *OrderItemProto) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// GetOrderRequest looks up a full order by ID.
// Called by Payment, Delivery, Review services.
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CustomerId    string                 `protobuf:"bytes,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	StoreId       string                 `protobuf:"bytes,5,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,6,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"` // empty for PICKUP
	Fulfillment   string                 `protobuf:"bytes,7,opt,name=fulfillment,proto3" json:"fulfillment,omitempty"`                 // DELIVERY | PICKUP
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,9,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`  // COD | MOMO | WALLET
	PaymentStatus string                 `protobuf:"bytes,10,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"` // UNPAID | PAID
	ItemsTotal    int64                  `protobuf:"varint,11,opt,name=items_total,json=itemsTotal,proto3" json:"items_total,omitempty"`
	ShipFee       int64                  `protobuf:"varint,12,opt,name=ship_fee,json=shipFee,proto3" json:"ship_fee,omitempty"`
	Discount      int64                  `protobuf:"varint,13,opt,name=discount,proto3" json:"discount,omitempty"`
	GrandTotal    int64                  `protobuf:"varint,14,opt,name=grand_total,json=grandTotal,proto3" json:"grand_total,omitempty"`
	PickupPin     string                 `protobuf:"bytes,15,opt,name=pickup_pin,json=pickupPin,proto3" json:"pickup_pin,omitempty"` // non-empty for PICKUP orders
	PlacedAt      string                 `protobuf:"bytes,16,opt,name=placed_at,json=placedAt,proto3" json:"placed_at,omitempty"`    // RFC3339
	Items         []*OrderItemProto      `protobuf:"bytes,17,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_proto_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetOrderResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetOrderResponse) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *GetOrderResponse) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *GetOrderResponse) GetFulfillment() string {
	if x != nil {
		return x.Fulfillment
	}
	return ""
}

func (x *GetOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *GetOrderResponse) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *GetOrderResponse) GetItemsTotal() int64 {
	if x != nil {
		return x.ItemsTotal
	}
	return 0
}

func (x *GetOrderResponse) GetShipFee() int64 {
	if x != nil {
		return x.ShipFee
	}
	return 0
}

func (x *GetOrderResponse) GetDiscount() int64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *GetOrderResponse) GetGrandTotal() int64 {
	if x != nil {
		return x.GrandTotal
	}
	return 0
}

func (x *GetOrderResponse) GetPickupPin() string {
	if x != nil {
		return x.PickupPin
	}
	return ""
}

func (x *GetOrderResponse) GetPlacedAt() string {
	if x != nil {
		return x.PlacedAt
	}
	return ""
}

func (x *GetOrderResponse) GetItems() []*OrderItemProto {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_order_v1_order_proto protoreflect.FileDescriptor

const file_proto_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/order/v1/order.proto\x12\border.v1\"\xc1\x01\n" +
	"\x0eOrderItemProto\x12 \n" +
	"\fmenu_item_id\x18\x01 \x01(\tR\n" +
	"menuItemId\x12#\n" +
	"\rname_snapshot\x18\x02 \x01(\tR\fnameSnapshot\x12%\n" +
	"\x0eprice_snapshot\x18\x03 \x01(\x03R\rpriceSnapshot\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x05R\x03qty\x12\x1b\n" +
	"\tcutoff_id\x18\x05 \x01(\tR\bcutoffId\x12\x12\n" +
	"\x04date\x18\x06 \x01(\tR\x04date\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xa1\x04\n" +
	"\x10GetOrderResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x1f\n" +
	"\vcustomer_id\x18\x04 \x01(\tR\n" +
	"customerId\x12\x19\n" +
	"\bstore_id\x18\x05 \x01(\tR\astoreId\x12\x1f\n" +
	"\vlocation_id\x18\x06 \x01(\tR\n" +
	"locationId\x12 \n" +
	"\vfulfillment\x18\a \x01(\tR\vfulfillment\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12%\n" +
	"\x0epayment_method\x18\t \x01(\tR\rpaymentMethod\x12%\n" +
	"\x0epayment_status\x18\n" +
	" \x01(\tR\rpaymentStatus\x12\x1f\n" +
	"\vitems_total\x18\v \x01(\x03R\n" +
	"itemsTotal\x12\x19\n" +
	"\bship_fee\x18\f \x01(\x03R\ashipFee\x12\x1a\n" +
	"\bdiscount\x18\r \x01(\x03R\bdiscount\x12\x1f\n" +
	"\vgrand_total\x18\x0e \x01(\x03R\n" +
	"grandTotal\x12\x1d\n" +
	"\n" +
	"pickup_pin\x18\x0f \x01(\tR\tpickupPin\x12\x1b\n" +
	"\tplaced_at\x18\x10 \x01(\tR\bplacedAt\x12.\n" +
	"\x05items\x18\x11 \x03(\v2\x18.order.v1.OrderItemProtoR\x05items2Q\n" +
	"\fOrderService\x12A\n" +
	"\bGetOrder\x12\x19.order.v1.GetOrderRequest\x1a\x1a.order.v1.GetOrderResponseB Z\x1eproject/proto/order/v1;orderv1b\x06proto3"

var (
	file_proto_order_v1_order_proto_rawDescOnce sync.Once
	file_proto_order_v1_order_proto_rawDescData []byte
)

func file_proto_order_v1_order_proto_rawDescGZIP() []byte {
	file_proto_order_v1_order_proto_rawDescOnce.Do(func() {
		file_proto_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_v1_order_proto_rawDesc), len(file_proto_order_v1_order_proto_rawDesc)))
	})
	return file_proto_order_v1_order_proto_rawDescData
}

var file_proto_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_order_v1_order_proto_goTypes = []any{
	(*OrderItemProto)(nil),   // 0: order.v1.OrderItemProto
	(*GetOrderRequest)(nil),  // 1: order.v1.GetOrderRequest
	(*GetOrderResponse)(nil), // 2: order.v1.GetOrderResponse
}
var file_proto_order_v1_order_proto_depIdxs = []int32{
	0, // 0: order.v1.GetOrderResponse.items:type_name -> order.v1.OrderItemProto
	1, // 1: order.v1.OrderService.GetOrder:input_type -> order.v1.GetOrderRequest
	2, // 2: order.v1.OrderService.GetOrder:output_type -> order.v1.GetOrderResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_order_v1_order_proto_init() }
func file_proto_order_v1_order_proto_init() {
	if File_proto_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_v1_order_proto_rawDesc), len(file_proto_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_order_v1_order_proto_goTypes,
		DependencyIndexes: file_proto_order_v1_order_proto_depIdxs,
		MessageInfos:      file_proto_order_v1_order_proto_msgTypes,
	}.Build()
	File_proto_order_v1_order_proto = out.File
	file_proto_order_v1_order_proto_goTypes = nil
	file_proto_order_v1_order_proto_depIdxs = nil
}
