app:
  env: production
  port: 8082
  grpc_port: 50053
  base_url: http://localhost:8082
  cookie_secure: false
  cookie_domain: ""

database:
  host: postgres
  port: 5432
  user: dev_user
  password: dev_password
  name: store_db
  ssl_mode: disable
  auto_migrate: true
  migrations_path: /migrations

redis:
  addr: redis:6379
  password: ""
  db: 0

kafka:
  brokers:
    - kafka:9092

rabbitmq:
  url: amqp://dev_user:dev_password@rabbitmq:5672/

dtm:
  addr: dtm:36790

jwt:
  private_key_path: ""
  public_key_path: ""
  public_key_pem: ""
  private_key_pem: ""
  access_ttl: 15m
  refresh_ttl: 168h

outbox:
  tick_every: 2s
  batch_size: 50
  max_attempts: 5

minio:
  endpoint: "minio:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket: "veloxfood"
  use_ssl: false

user_service:
  grpc_addr: user-service:50051
location_service:
  grpc_addr: location-service:50052
