// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/store/v1/store.proto

package storev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderItem is a single sellable item returned for order validation.
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_store_v1_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// GetStoreForOrderRequest is called by the order service before placing an order.
type GetStoreForOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreForOrderRequest) Reset() {
	*x = GetStoreForOrderRequest{}
	mi := &file_proto_store_v1_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreForOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreForOrderRequest) ProtoMessage() {}

func (x *GetStoreForOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreForOrderRequest.ProtoReflect.Descriptor instead.
func (*GetStoreForOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{1}
}

func (x *GetStoreForOrderRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *GetStoreForOrderRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// CutoffInfo describes one delivery session (ca) so the order service can
// compute each item's actual cutoff deadline (date + cutoff_time - lead).
type CutoffInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CutoffTime    string                 `protobuf:"bytes,2,opt,name=cutoff_time,json=cutoffTime,proto3" json:"cutoff_time,omitempty"` // HH:MM
	LeadMinutes   int32                  `protobuf:"varint,3,opt,name=lead_minutes,json=leadMinutes,proto3" json:"lead_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CutoffInfo) Reset() {
	*x = CutoffInfo{}
	mi := &file_proto_store_v1_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CutoffInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutoffInfo) ProtoMessage() {}

func (x *CutoffInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutoffInfo.ProtoReflect.Descriptor instead.
func (*CutoffInfo) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{2}
}

func (x *CutoffInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CutoffInfo) GetCutoffTime() string {
	if x != nil {
		return x.CutoffTime
	}
	return ""
}

func (x *CutoffInfo) GetLeadMinutes() int32 {
	if x != nil {
		return x.LeadMinutes
	}
	return 0
}

type GetStoreForOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	SaleStatus    string                 `protobuf:"bytes,2,opt,name=sale_status,json=saleStatus,proto3" json:"sale_status,omitempty"`
	UnitShipFee   int64                  `protobuf:"varint,3,opt,name=unit_ship_fee,json=unitShipFee,proto3" json:"unit_ship_fee,omitempty"`
	Served        bool                   `protobuf:"varint,4,opt,name=served,proto3" json:"served,omitempty"` // true when the room is covered by a ship fee rule
	Items         []*OrderItem           `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	OrderDeadline string                 `protobuf:"bytes,6,opt,name=order_deadline,json=orderDeadline,proto3" json:"order_deadline,omitempty"` // ISO-8601 datetime string (latest cutoff - lead)
	Cutoffs       []*CutoffInfo          `protobuf:"bytes,7,rep,name=cutoffs,proto3" json:"cutoffs,omitempty"`                                  // store's ship cutoffs (for per-item deadline)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreForOrderResponse) Reset() {
	*x = GetStoreForOrderResponse{}
	mi := &file_proto_store_v1_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreForOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreForOrderResponse) ProtoMessage() {}

func (x *GetStoreForOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreForOrderResponse.ProtoReflect.Descriptor instead.
func (*GetStoreForOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{3}
}

func (x *GetStoreForOrderResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetStoreForOrderResponse) GetSaleStatus() string {
	if x != nil {
		return x.SaleStatus
	}
	return ""
}

func (x *GetStoreForOrderResponse) GetUnitShipFee() int64 {
	if x != nil {
		return x.UnitShipFee
	}
	return 0
}

func (x *GetStoreForOrderResponse) GetServed() bool {
	if x != nil {
		return x.Served
	}
	return false
}

func (x *GetStoreForOrderResponse) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetStoreForOrderResponse) GetOrderDeadline() string {
	if x != nil {
		return x.OrderDeadline
	}
	return ""
}

func (x *GetStoreForOrderResponse) GetCutoffs() []*CutoffInfo {
	if x != nil {
		return x.Cutoffs
	}
	return nil
}

// DecrementSlotQuotaRequest is called when an order is placed.
type DecrementSlotQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	CutoffId      string                 `protobuf:"bytes,2,opt,name=cutoff_id,json=cutoffId,proto3" json:"cutoff_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	Qty           int32                  `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrementSlotQuotaRequest) Reset() {
	*x = DecrementSlotQuotaRequest{}
	mi := &file_proto_store_v1_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrementSlotQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementSlotQuotaRequest) ProtoMessage() {}

func (x *DecrementSlotQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementSlotQuotaRequest.ProtoReflect.Descriptor instead.
func (*DecrementSlotQuotaRequest) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{4}
}

func (x *DecrementSlotQuotaRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *DecrementSlotQuotaRequest) GetCutoffId() string {
	if x != nil {
		return x.CutoffId
	}
	return ""
}

func (x *DecrementSlotQuotaRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DecrementSlotQuotaRequest) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type DecrementSlotQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Remaining     int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrementSlotQuotaResponse) Reset() {
	*x = DecrementSlotQuotaResponse{}
	mi := &file_proto_store_v1_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrementSlotQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementSlotQuotaResponse) ProtoMessage() {}

func (x *DecrementSlotQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementSlotQuotaResponse.ProtoReflect.Descriptor instead.
func (*DecrementSlotQuotaResponse) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{5}
}

func (x *DecrementSlotQuotaResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DecrementSlotQuotaResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

// RestoreSlotQuotaRequest is called on saga compensation or order cancellation.
type RestoreSlotQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	CutoffId      string                 `protobuf:"bytes,2,opt,name=cutoff_id,json=cutoffId,proto3" json:"cutoff_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD
	Qty           int32                  `protobuf:"varint,4,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSlotQuotaRequest) Reset() {
	*x = RestoreSlotQuotaRequest{}
	mi := &file_proto_store_v1_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSlotQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSlotQuotaRequest) ProtoMessage() {}

func (x *RestoreSlotQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSlotQuotaRequest.ProtoReflect.Descriptor instead.
func (*RestoreSlotQuotaRequest) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreSlotQuotaRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RestoreSlotQuotaRequest) GetCutoffId() string {
	if x != nil {
		return x.CutoffId
	}
	return ""
}

func (x *RestoreSlotQuotaRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RestoreSlotQuotaRequest) GetQty() int32 {
	if x != nil {
		return x.Qty
	}
	return 0
}

type RestoreSlotQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreSlotQuotaResponse) Reset() {
	*x = RestoreSlotQuotaResponse{}
	mi := &file_proto_store_v1_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreSlotQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreSlotQuotaResponse) ProtoMessage() {}

func (x *RestoreSlotQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreSlotQuotaResponse.ProtoReflect.Descriptor instead.
func (*RestoreSlotQuotaResponse) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{7}
}

func (x *RestoreSlotQuotaResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// GetStoreOwnershipRequest looks up the ownership record for a store so that
// callers can verify vendor_id without holding store data themselves.
type GetStoreOwnershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreOwnershipRequest) Reset() {
	*x = GetStoreOwnershipRequest{}
	mi := &file_proto_store_v1_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreOwnershipRequest) ProtoMessage() {}

func (x *GetStoreOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreOwnershipRequest.ProtoReflect.Descriptor instead.
func (*GetStoreOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{8}
}

func (x *GetStoreOwnershipRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type GetStoreOwnershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	VendorId      string                 `protobuf:"bytes,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreOwnershipResponse) Reset() {
	*x = GetStoreOwnershipResponse{}
	mi := &file_proto_store_v1_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreOwnershipResponse) ProtoMessage() {}

func (x *GetStoreOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreOwnershipResponse.ProtoReflect.Descriptor instead.
func (*GetStoreOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{9}
}

func (x *GetStoreOwnershipResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetStoreOwnershipResponse) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *GetStoreOwnershipResponse) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *GetStoreOwnershipResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_store_v1_store_proto protoreflect.FileDescriptor

const file_proto_store_v1_store_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/store/v1/store.proto\x12\bstore.v1\"N\n" +
	"\tOrderItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\"M\n" +
	"\x17GetStoreForOrderRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"`\n" +
	"\n" +
	"CutoffInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcutoff_time\x18\x02 \x01(\tR\n" +
	"cutoffTime\x12!\n" +
	"\flead_minutes\x18\x03 \x01(\x05R\vleadMinutes\"\x8f\x02\n" +
	"\x18GetStoreForOrderResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1f\n" +
	"\vsale_status\x18\x02 \x01(\tR\n" +
	"saleStatus\x12\"\n" +
	"\runit_ship_fee\x18\x03 \x01(\x03R\vunitShipFee\x12\x16\n" +
	"\x06served\x18\x04 \x01(\bR\x06served\x12)\n" +
	"\x05items\x18\x05 \x03(\v2\x13.store.v1.OrderItemR\x05items\x12%\n" +
	"\x0eorder_deadline\x18\x06 \x01(\tR\rorderDeadline\x12.\n" +
	"\acutoffs\x18\a \x03(\v2\x14.store.v1.CutoffInfoR\acutoffs\"w\n" +
	"\x19DecrementSlotQuotaRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\tcutoff_id\x18\x02 \x01(\tR\bcutoffId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x05R\x03qty\"J\n" +
	"\x1aDecrementSlotQuotaResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\"u\n" +
	"\x17RestoreSlotQuotaRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\tcutoff_id\x18\x02 \x01(\tR\bcutoffId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x10\n" +
	"\x03qty\x18\x04 \x01(\x05R\x03qty\"*\n" +
	"\x18RestoreSlotQuotaResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"5\n" +
	"\x18GetStoreOwnershipRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"\x86\x01\n" +
	"\x19GetStoreOwnershipResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\tR\bvendorId\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name2\x83\x03\n" +
	"\fStoreService\x12Y\n" +
	"\x10GetStoreForOrder\x12!.store.v1.GetStoreForOrderRequest\x1a\".store.v1.GetStoreForOrderResponse\x12_\n" +
	"\x12DecrementSlotQuota\x12#.store.v1.DecrementSlotQuotaRequest\x1a$.store.v1.DecrementSlotQuotaResponse\x12Y\n" +
	"\x10RestoreSlotQuota\x12!.store.v1.RestoreSlotQuotaRequest\x1a\".store.v1.RestoreSlotQuotaResponse\x12\\\n" +
	"\x11GetStoreOwnership\x12\".store.v1.GetStoreOwnershipRequest\x1a#.store.v1.GetStoreOwnershipResponseB Z\x1eproject/proto/store/v1;storev1b\x06proto3"

var (
	file_proto_store_v1_store_proto_rawDescOnce sync.Once
	file_proto_store_v1_store_proto_rawDescData []byte
)

func file_proto_store_v1_store_proto_rawDescGZIP() []byte {
	file_proto_store_v1_store_proto_rawDescOnce.Do(func() {
		file_proto_store_v1_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_store_v1_store_proto_rawDesc), len(file_proto_store_v1_store_proto_rawDesc)))
	})
	return file_proto_store_v1_store_proto_rawDescData
}

var file_proto_store_v1_store_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_store_v1_store_proto_goTypes = []any{
	(*OrderItem)(nil),                  // 0: store.v1.OrderItem
	(*GetStoreForOrderRequest)(nil),    // 1: store.v1.GetStoreForOrderRequest
	(*CutoffInfo)(nil),                 // 2: store.v1.CutoffInfo
	(*GetStoreForOrderResponse)(nil),   // 3: store.v1.GetStoreForOrderResponse
	(*DecrementSlotQuotaRequest)(nil),  // 4: store.v1.DecrementSlotQuotaRequest
	(*DecrementSlotQuotaResponse)(nil), // 5: store.v1.DecrementSlotQuotaResponse
	(*RestoreSlotQuotaRequest)(nil),    // 6: store.v1.RestoreSlotQuotaRequest
	(*RestoreSlotQuotaResponse)(nil),   // 7: store.v1.RestoreSlotQuotaResponse
	(*GetStoreOwnershipRequest)(nil),   // 8: store.v1.GetStoreOwnershipRequest
	(*GetStoreOwnershipResponse)(nil),  // 9: store.v1.GetStoreOwnershipResponse
}
var file_proto_store_v1_store_proto_depIdxs = []int32{
	0, // 0: store.v1.GetStoreForOrderResponse.items:type_name -> store.v1.OrderItem
	2, // 1: store.v1.GetStoreForOrderResponse.cutoffs:type_name -> store.v1.CutoffInfo
	1, // 2: store.v1.StoreService.GetStoreForOrder:input_type -> store.v1.GetStoreForOrderRequest
	4, // 3: store.v1.StoreService.DecrementSlotQuota:input_type -> store.v1.DecrementSlotQuotaRequest
	6, // 4: store.v1.StoreService.RestoreSlotQuota:input_type -> store.v1.RestoreSlotQuotaRequest
	8, // 5: store.v1.StoreService.GetStoreOwnership:input_type -> store.v1.GetStoreOwnershipRequest
	3, // 6: store.v1.StoreService.GetStoreForOrder:output_type -> store.v1.GetStoreForOrderResponse
	5, // 7: store.v1.StoreService.DecrementSlotQuota:output_type -> store.v1.DecrementSlotQuotaResponse
	7, // 8: store.v1.StoreService.RestoreSlotQuota:output_type -> store.v1.RestoreSlotQuotaResponse
	9, // 9: store.v1.StoreService.GetStoreOwnership:output_type -> store.v1.GetStoreOwnershipResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_store_v1_store_proto_init() }
func file_proto_store_v1_store_proto_init() {
	if File_proto_store_v1_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_store_v1_store_proto_rawDesc), len(file_proto_store_v1_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_store_v1_store_proto_goTypes,
		DependencyIndexes: file_proto_store_v1_store_proto_depIdxs,
		MessageInfos:      file_proto_store_v1_store_proto_msgTypes,
	}.Build()
	File_proto_store_v1_store_proto = out.File
	file_proto_store_v1_store_proto_goTypes = nil
	file_proto_store_v1_store_proto_depIdxs = nil
}
