// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/store/v1/store.proto

package storev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderItem is a single sellable item returned for order validation.
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_proto_store_v1_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *OrderItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// GetStoreForOrderRequest is called by the order service before placing an order.
type GetStoreForOrderRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	StoreId string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	// room_id carries the delivery location id at the level given by location_level
	// (room id for ROOM, floor id for FLOOR, building id for BUILDING). Empty for PICKUP.
	// Field kept named room_id for backward compatibility.
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// location_level: "ROOM" | "FLOOR" | "BUILDING". Empty ⇒ treated as ROOM.
	LocationLevel string `protobuf:"bytes,3,opt,name=location_level,json=locationLevel,proto3" json:"location_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreForOrderRequest) Reset() {
	*x = GetStoreForOrderRequest{}
	mi := &file_proto_store_v1_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreForOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreForOrderRequest) ProtoMessage() {}

func (x *GetStoreForOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreForOrderRequest.ProtoReflect.Descriptor instead.
func (*GetStoreForOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{1}
}

func (x *GetStoreForOrderRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *GetStoreForOrderRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetStoreForOrderRequest) GetLocationLevel() string {
	if x != nil {
		return x.LocationLevel
	}
	return ""
}

type GetStoreForOrderResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Found       bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	SaleStatus  string                 `protobuf:"bytes,2,opt,name=sale_status,json=saleStatus,proto3" json:"sale_status,omitempty"`
	UnitShipFee int64                  `protobuf:"varint,3,opt,name=unit_ship_fee,json=unitShipFee,proto3" json:"unit_ship_fee,omitempty"`
	Served      bool                   `protobuf:"varint,4,opt,name=served,proto3" json:"served,omitempty"` // true when the room is covered by a ship fee rule
	Items       []*OrderItem           `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	// Delivery-time model: prep_minutes is the store's minimum preparation time;
	// open_now reflects SaleStatus + today's operating hours; open/close_time_today
	// are today's window (HH:MM, empty when closed today). The order service uses
	// these to validate the customer's desired receive time.
	PrepMinutes    int32  `protobuf:"varint,6,opt,name=prep_minutes,json=prepMinutes,proto3" json:"prep_minutes,omitempty"`
	OpenNow        bool   `protobuf:"varint,7,opt,name=open_now,json=openNow,proto3" json:"open_now,omitempty"`
	OpenTimeToday  string `protobuf:"bytes,8,opt,name=open_time_today,json=openTimeToday,proto3" json:"open_time_today,omitempty"`    // HH:MM, empty if closed today
	CloseTimeToday string `protobuf:"bytes,9,opt,name=close_time_today,json=closeTimeToday,proto3" json:"close_time_today,omitempty"` // HH:MM, empty if closed today
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStoreForOrderResponse) Reset() {
	*x = GetStoreForOrderResponse{}
	mi := &file_proto_store_v1_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreForOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreForOrderResponse) ProtoMessage() {}

func (x *GetStoreForOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreForOrderResponse.ProtoReflect.Descriptor instead.
func (*GetStoreForOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{2}
}

func (x *GetStoreForOrderResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetStoreForOrderResponse) GetSaleStatus() string {
	if x != nil {
		return x.SaleStatus
	}
	return ""
}

func (x *GetStoreForOrderResponse) GetUnitShipFee() int64 {
	if x != nil {
		return x.UnitShipFee
	}
	return 0
}

func (x *GetStoreForOrderResponse) GetServed() bool {
	if x != nil {
		return x.Served
	}
	return false
}

func (x *GetStoreForOrderResponse) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetStoreForOrderResponse) GetPrepMinutes() int32 {
	if x != nil {
		return x.PrepMinutes
	}
	return 0
}

func (x *GetStoreForOrderResponse) GetOpenNow() bool {
	if x != nil {
		return x.OpenNow
	}
	return false
}

func (x *GetStoreForOrderResponse) GetOpenTimeToday() string {
	if x != nil {
		return x.OpenTimeToday
	}
	return ""
}

func (x *GetStoreForOrderResponse) GetCloseTimeToday() string {
	if x != nil {
		return x.CloseTimeToday
	}
	return ""
}

// GetStoreOwnershipRequest looks up the ownership record for a store so that
// callers can verify vendor_id without holding store data themselves.
type GetStoreOwnershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreOwnershipRequest) Reset() {
	*x = GetStoreOwnershipRequest{}
	mi := &file_proto_store_v1_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreOwnershipRequest) ProtoMessage() {}

func (x *GetStoreOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreOwnershipRequest.ProtoReflect.Descriptor instead.
func (*GetStoreOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{3}
}

func (x *GetStoreOwnershipRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

type GetStoreOwnershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	VendorId      string                 `protobuf:"bytes,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	OwnerUserId   string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreOwnershipResponse) Reset() {
	*x = GetStoreOwnershipResponse{}
	mi := &file_proto_store_v1_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreOwnershipResponse) ProtoMessage() {}

func (x *GetStoreOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_store_v1_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreOwnershipResponse.ProtoReflect.Descriptor instead.
func (*GetStoreOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_proto_store_v1_store_proto_rawDescGZIP(), []int{4}
}

func (x *GetStoreOwnershipResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetStoreOwnershipResponse) GetVendorId() string {
	if x != nil {
		return x.VendorId
	}
	return ""
}

func (x *GetStoreOwnershipResponse) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *GetStoreOwnershipResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_store_v1_store_proto protoreflect.FileDescriptor

const file_proto_store_v1_store_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/store/v1/store.proto\x12\bstore.v1\"N\n" +
	"\tOrderItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\"t\n" +
	"\x17GetStoreForOrderRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12%\n" +
	"\x0elocation_level\x18\x03 \x01(\tR\rlocationLevel\"\xc8\x02\n" +
	"\x18GetStoreForOrderResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1f\n" +
	"\vsale_status\x18\x02 \x01(\tR\n" +
	"saleStatus\x12\"\n" +
	"\runit_ship_fee\x18\x03 \x01(\x03R\vunitShipFee\x12\x16\n" +
	"\x06served\x18\x04 \x01(\bR\x06served\x12)\n" +
	"\x05items\x18\x05 \x03(\v2\x13.store.v1.OrderItemR\x05items\x12!\n" +
	"\fprep_minutes\x18\x06 \x01(\x05R\vprepMinutes\x12\x19\n" +
	"\bopen_now\x18\a \x01(\bR\aopenNow\x12&\n" +
	"\x0fopen_time_today\x18\b \x01(\tR\ropenTimeToday\x12(\n" +
	"\x10close_time_today\x18\t \x01(\tR\x0ecloseTimeToday\"5\n" +
	"\x18GetStoreOwnershipRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"\x86\x01\n" +
	"\x19GetStoreOwnershipResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\tR\bvendorId\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name2\xc7\x01\n" +
	"\fStoreService\x12Y\n" +
	"\x10GetStoreForOrder\x12!.store.v1.GetStoreForOrderRequest\x1a\".store.v1.GetStoreForOrderResponse\x12\\\n" +
	"\x11GetStoreOwnership\x12\".store.v1.GetStoreOwnershipRequest\x1a#.store.v1.GetStoreOwnershipResponseB Z\x1eproject/proto/store/v1;storev1b\x06proto3"

var (
	file_proto_store_v1_store_proto_rawDescOnce sync.Once
	file_proto_store_v1_store_proto_rawDescData []byte
)

func file_proto_store_v1_store_proto_rawDescGZIP() []byte {
	file_proto_store_v1_store_proto_rawDescOnce.Do(func() {
		file_proto_store_v1_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_store_v1_store_proto_rawDesc), len(file_proto_store_v1_store_proto_rawDesc)))
	})
	return file_proto_store_v1_store_proto_rawDescData
}

var file_proto_store_v1_store_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_store_v1_store_proto_goTypes = []any{
	(*OrderItem)(nil),                 // 0: store.v1.OrderItem
	(*GetStoreForOrderRequest)(nil),   // 1: store.v1.GetStoreForOrderRequest
	(*GetStoreForOrderResponse)(nil),  // 2: store.v1.GetStoreForOrderResponse
	(*GetStoreOwnershipRequest)(nil),  // 3: store.v1.GetStoreOwnershipRequest
	(*GetStoreOwnershipResponse)(nil), // 4: store.v1.GetStoreOwnershipResponse
}
var file_proto_store_v1_store_proto_depIdxs = []int32{
	0, // 0: store.v1.GetStoreForOrderResponse.items:type_name -> store.v1.OrderItem
	1, // 1: store.v1.StoreService.GetStoreForOrder:input_type -> store.v1.GetStoreForOrderRequest
	3, // 2: store.v1.StoreService.GetStoreOwnership:input_type -> store.v1.GetStoreOwnershipRequest
	2, // 3: store.v1.StoreService.GetStoreForOrder:output_type -> store.v1.GetStoreForOrderResponse
	4, // 4: store.v1.StoreService.GetStoreOwnership:output_type -> store.v1.GetStoreOwnershipResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_store_v1_store_proto_init() }
func file_proto_store_v1_store_proto_init() {
	if File_proto_store_v1_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_store_v1_store_proto_rawDesc), len(file_proto_store_v1_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_store_v1_store_proto_goTypes,
		DependencyIndexes: file_proto_store_v1_store_proto_depIdxs,
		MessageInfos:      file_proto_store_v1_store_proto_msgTypes,
	}.Build()
	File_proto_store_v1_store_proto = out.File
	file_proto_store_v1_store_proto_goTypes = nil
	file_proto_store_v1_store_proto_depIdxs = nil
}
