// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/store/v1/store.proto

package storev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoreService_GetStoreForOrder_FullMethodName   = "/store.v1.StoreService/GetStoreForOrder"
	StoreService_DecrementSlotQuota_FullMethodName = "/store.v1.StoreService/DecrementSlotQuota"
	StoreService_GetStoreOwnership_FullMethodName  = "/store.v1.StoreService/GetStoreOwnership"
)

// StoreServiceClient is the client API for StoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreServiceClient interface {
	// GetStoreForOrder assembles store availability, ship fee, and menu snapshot
	// for the order service before order placement.
	GetStoreForOrder(ctx context.Context, in *GetStoreForOrderRequest, opts ...grpc.CallOption) (*GetStoreForOrderResponse, error)
	// DecrementSlotQuota atomically reduces sold count for a quota slot.
	// Returns ok=false if quota is exhausted.
	DecrementSlotQuota(ctx context.Context, in *DecrementSlotQuotaRequest, opts ...grpc.CallOption) (*DecrementSlotQuotaResponse, error)
	// GetStoreOwnership returns the vendor_id and owner_user_id for a store so
	// peer services (e.g. promotion) can authorise store-scoped mutations without
	// holding a local copy of store data.
	GetStoreOwnership(ctx context.Context, in *GetStoreOwnershipRequest, opts ...grpc.CallOption) (*GetStoreOwnershipResponse, error)
}

type storeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreServiceClient(cc grpc.ClientConnInterface) StoreServiceClient {
	return &storeServiceClient{cc}
}

func (c *storeServiceClient) GetStoreForOrder(ctx context.Context, in *GetStoreForOrderRequest, opts ...grpc.CallOption) (*GetStoreForOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStoreForOrderResponse)
	err := c.cc.Invoke(ctx, StoreService_GetStoreForOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) DecrementSlotQuota(ctx context.Context, in *DecrementSlotQuotaRequest, opts ...grpc.CallOption) (*DecrementSlotQuotaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecrementSlotQuotaResponse)
	err := c.cc.Invoke(ctx, StoreService_DecrementSlotQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeServiceClient) GetStoreOwnership(ctx context.Context, in *GetStoreOwnershipRequest, opts ...grpc.CallOption) (*GetStoreOwnershipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStoreOwnershipResponse)
	err := c.cc.Invoke(ctx, StoreService_GetStoreOwnership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServiceServer is the server API for StoreService service.
// All implementations must embed UnimplementedStoreServiceServer
// for forward compatibility.
type StoreServiceServer interface {
	// GetStoreForOrder assembles store availability, ship fee, and menu snapshot
	// for the order service before order placement.
	GetStoreForOrder(context.Context, *GetStoreForOrderRequest) (*GetStoreForOrderResponse, error)
	// DecrementSlotQuota atomically reduces sold count for a quota slot.
	// Returns ok=false if quota is exhausted.
	DecrementSlotQuota(context.Context, *DecrementSlotQuotaRequest) (*DecrementSlotQuotaResponse, error)
	// GetStoreOwnership returns the vendor_id and owner_user_id for a store so
	// peer services (e.g. promotion) can authorise store-scoped mutations without
	// holding a local copy of store data.
	GetStoreOwnership(context.Context, *GetStoreOwnershipRequest) (*GetStoreOwnershipResponse, error)
	mustEmbedUnimplementedStoreServiceServer()
}

// UnimplementedStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServiceServer struct{}

func (UnimplementedStoreServiceServer) GetStoreForOrder(context.Context, *GetStoreForOrderRequest) (*GetStoreForOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStoreForOrder not implemented")
}
func (UnimplementedStoreServiceServer) DecrementSlotQuota(context.Context, *DecrementSlotQuotaRequest) (*DecrementSlotQuotaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecrementSlotQuota not implemented")
}
func (UnimplementedStoreServiceServer) GetStoreOwnership(context.Context, *GetStoreOwnershipRequest) (*GetStoreOwnershipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStoreOwnership not implemented")
}
func (UnimplementedStoreServiceServer) mustEmbedUnimplementedStoreServiceServer() {}
func (UnimplementedStoreServiceServer) testEmbeddedByValue()                      {}

// UnsafeStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServiceServer will
// result in compilation errors.
type UnsafeStoreServiceServer interface {
	mustEmbedUnimplementedStoreServiceServer()
}

func RegisterStoreServiceServer(s grpc.ServiceRegistrar, srv StoreServiceServer) {
	// If the following call panics, it indicates UnimplementedStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoreService_ServiceDesc, srv)
}

func _StoreService_GetStoreForOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreForOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetStoreForOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetStoreForOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetStoreForOrder(ctx, req.(*GetStoreForOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_DecrementSlotQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrementSlotQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).DecrementSlotQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_DecrementSlotQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).DecrementSlotQuota(ctx, req.(*DecrementSlotQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreService_GetStoreOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreOwnershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServiceServer).GetStoreOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreService_GetStoreOwnership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServiceServer).GetStoreOwnership(ctx, req.(*GetStoreOwnershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreService_ServiceDesc is the grpc.ServiceDesc for StoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "store.v1.StoreService",
	HandlerType: (*StoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStoreForOrder",
			Handler:    _StoreService_GetStoreForOrder_Handler,
		},
		{
			MethodName: "DecrementSlotQuota",
			Handler:    _StoreService_DecrementSlotQuota_Handler,
		},
		{
			MethodName: "GetStoreOwnership",
			Handler:    _StoreService_GetStoreOwnership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/store/v1/store.proto",
}
