// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/review/v1/review.proto

package reviewv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetStoreRatingSummaryRequest carries the store_id to summarise.
type GetStoreRatingSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreRatingSummaryRequest) Reset() {
	*x = GetStoreRatingSummaryRequest{}
	mi := &file_proto_review_v1_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreRatingSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreRatingSummaryRequest) ProtoMessage() {}

func (x *GetStoreRatingSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_v1_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreRatingSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetStoreRatingSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_review_v1_review_proto_rawDescGZIP(), []int{0}
}

func (x *GetStoreRatingSummaryRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

// GetStoreRatingSummaryResponse returns the average rating and visible review count.
type GetStoreRatingSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avg           float64                `protobuf:"fixed64,1,opt,name=avg,proto3" json:"avg,omitempty"`    // average rating of VISIBLE reviews; 0 when count=0
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // total number of VISIBLE reviews for the store
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreRatingSummaryResponse) Reset() {
	*x = GetStoreRatingSummaryResponse{}
	mi := &file_proto_review_v1_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreRatingSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreRatingSummaryResponse) ProtoMessage() {}

func (x *GetStoreRatingSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_review_v1_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreRatingSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetStoreRatingSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_review_v1_review_proto_rawDescGZIP(), []int{1}
}

func (x *GetStoreRatingSummaryResponse) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *GetStoreRatingSummaryResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_review_v1_review_proto protoreflect.FileDescriptor

const file_proto_review_v1_review_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/review/v1/review.proto\x12\treview.v1\"9\n" +
	"\x1cGetStoreRatingSummaryRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\"G\n" +
	"\x1dGetStoreRatingSummaryResponse\x12\x10\n" +
	"\x03avg\x18\x01 \x01(\x01R\x03avg\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2{\n" +
	"\rReviewService\x12j\n" +
	"\x15GetStoreRatingSummary\x12'.review.v1.GetStoreRatingSummaryRequest\x1a(.review.v1.GetStoreRatingSummaryResponseB\"Z project/proto/review/v1;reviewv1b\x06proto3"

var (
	file_proto_review_v1_review_proto_rawDescOnce sync.Once
	file_proto_review_v1_review_proto_rawDescData []byte
)

func file_proto_review_v1_review_proto_rawDescGZIP() []byte {
	file_proto_review_v1_review_proto_rawDescOnce.Do(func() {
		file_proto_review_v1_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_review_v1_review_proto_rawDesc), len(file_proto_review_v1_review_proto_rawDesc)))
	})
	return file_proto_review_v1_review_proto_rawDescData
}

var file_proto_review_v1_review_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_review_v1_review_proto_goTypes = []any{
	(*GetStoreRatingSummaryRequest)(nil),  // 0: review.v1.GetStoreRatingSummaryRequest
	(*GetStoreRatingSummaryResponse)(nil), // 1: review.v1.GetStoreRatingSummaryResponse
}
var file_proto_review_v1_review_proto_depIdxs = []int32{
	0, // 0: review.v1.ReviewService.GetStoreRatingSummary:input_type -> review.v1.GetStoreRatingSummaryRequest
	1, // 1: review.v1.ReviewService.GetStoreRatingSummary:output_type -> review.v1.GetStoreRatingSummaryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_review_v1_review_proto_init() }
func file_proto_review_v1_review_proto_init() {
	if File_proto_review_v1_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_review_v1_review_proto_rawDesc), len(file_proto_review_v1_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_review_v1_review_proto_goTypes,
		DependencyIndexes: file_proto_review_v1_review_proto_depIdxs,
		MessageInfos:      file_proto_review_v1_review_proto_msgTypes,
	}.Build()
	File_proto_review_v1_review_proto = out.File
	file_proto_review_v1_review_proto_goTypes = nil
	file_proto_review_v1_review_proto_depIdxs = nil
}
