// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/location/v1/location.proto

package locationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Room delivery target resolved across the building/floor/room tree.
// location_id == room_id across the system.
type ResolvedRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomCode      string                 `protobuf:"bytes,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	RoomName      string                 `protobuf:"bytes,3,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	FloorId       string                 `protobuf:"bytes,4,opt,name=floor_id,json=floorId,proto3" json:"floor_id,omitempty"`
	FloorName     string                 `protobuf:"bytes,5,opt,name=floor_name,json=floorName,proto3" json:"floor_name,omitempty"`
	BuildingId    string                 `protobuf:"bytes,6,opt,name=building_id,json=buildingId,proto3" json:"building_id,omitempty"`
	BuildingName  string                 `protobuf:"bytes,7,opt,name=building_name,json=buildingName,proto3" json:"building_name,omitempty"`
	Active        bool                   `protobuf:"varint,8,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvedRoom) Reset() {
	*x = ResolvedRoom{}
	mi := &file_proto_location_v1_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvedRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedRoom) ProtoMessage() {}

func (x *ResolvedRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_v1_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedRoom.ProtoReflect.Descriptor instead.
func (*ResolvedRoom) Descriptor() ([]byte, []int) {
	return file_proto_location_v1_location_proto_rawDescGZIP(), []int{0}
}

func (x *ResolvedRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ResolvedRoom) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *ResolvedRoom) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *ResolvedRoom) GetFloorId() string {
	if x != nil {
		return x.FloorId
	}
	return ""
}

func (x *ResolvedRoom) GetFloorName() string {
	if x != nil {
		return x.FloorName
	}
	return ""
}

func (x *ResolvedRoom) GetBuildingId() string {
	if x != nil {
		return x.BuildingId
	}
	return ""
}

func (x *ResolvedRoom) GetBuildingName() string {
	if x != nil {
		return x.BuildingName
	}
	return ""
}

func (x *ResolvedRoom) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_proto_location_v1_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_v1_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_location_v1_location_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *ResolvedRoom          `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResponse) Reset() {
	*x = GetRoomResponse{}
	mi := &file_proto_location_v1_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResponse) ProtoMessage() {}

func (x *GetRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_location_v1_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_location_v1_location_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoomResponse) GetRoom() *ResolvedRoom {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *GetRoomResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_proto_location_v1_location_proto protoreflect.FileDescriptor

const file_proto_location_v1_location_proto_rawDesc = "" +
	"\n" +
	" proto/location/v1/location.proto\x12\vlocation.v1\"\xf9\x01\n" +
	"\fResolvedRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\troom_code\x18\x02 \x01(\tR\broomCode\x12\x1b\n" +
	"\troom_name\x18\x03 \x01(\tR\broomName\x12\x19\n" +
	"\bfloor_id\x18\x04 \x01(\tR\afloorId\x12\x1d\n" +
	"\n" +
	"floor_name\x18\x05 \x01(\tR\tfloorName\x12\x1f\n" +
	"\vbuilding_id\x18\x06 \x01(\tR\n" +
	"buildingId\x12#\n" +
	"\rbuilding_name\x18\a \x01(\tR\fbuildingName\x12\x16\n" +
	"\x06active\x18\b \x01(\bR\x06active\")\n" +
	"\x0eGetRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"V\n" +
	"\x0fGetRoomResponse\x12-\n" +
	"\x04room\x18\x01 \x01(\v2\x19.location.v1.ResolvedRoomR\x04room\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found2W\n" +
	"\x0fLocationService\x12D\n" +
	"\aGetRoom\x12\x1b.location.v1.GetRoomRequest\x1a\x1c.location.v1.GetRoomResponseB&Z$project/proto/location/v1;locationv1b\x06proto3"

var (
	file_proto_location_v1_location_proto_rawDescOnce sync.Once
	file_proto_location_v1_location_proto_rawDescData []byte
)

func file_proto_location_v1_location_proto_rawDescGZIP() []byte {
	file_proto_location_v1_location_proto_rawDescOnce.Do(func() {
		file_proto_location_v1_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_location_v1_location_proto_rawDesc), len(file_proto_location_v1_location_proto_rawDesc)))
	})
	return file_proto_location_v1_location_proto_rawDescData
}

var file_proto_location_v1_location_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_location_v1_location_proto_goTypes = []any{
	(*ResolvedRoom)(nil),    // 0: location.v1.ResolvedRoom
	(*GetRoomRequest)(nil),  // 1: location.v1.GetRoomRequest
	(*GetRoomResponse)(nil), // 2: location.v1.GetRoomResponse
}
var file_proto_location_v1_location_proto_depIdxs = []int32{
	0, // 0: location.v1.GetRoomResponse.room:type_name -> location.v1.ResolvedRoom
	1, // 1: location.v1.LocationService.GetRoom:input_type -> location.v1.GetRoomRequest
	2, // 2: location.v1.LocationService.GetRoom:output_type -> location.v1.GetRoomResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_location_v1_location_proto_init() }
func file_proto_location_v1_location_proto_init() {
	if File_proto_location_v1_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_location_v1_location_proto_rawDesc), len(file_proto_location_v1_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_location_v1_location_proto_goTypes,
		DependencyIndexes: file_proto_location_v1_location_proto_depIdxs,
		MessageInfos:      file_proto_location_v1_location_proto_msgTypes,
	}.Build()
	File_proto_location_v1_location_proto = out.File
	file_proto_location_v1_location_proto_goTypes = nil
	file_proto_location_v1_location_proto_depIdxs = nil
}
