// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/promotion/v1/promotion.proto

package promotionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApplyPromotionRequest is sent by the order service to reserve promotions before
// an order is confirmed. Each code maps to one promotion row.
type ApplyPromotionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	OrderId    string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StoreId    string                 `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	CustomerId string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Codes      []string               `protobuf:"bytes,4,rep,name=codes,proto3" json:"codes,omitempty"`
	Subtotal   int64                  `protobuf:"varint,5,opt,name=subtotal,proto3" json:"subtotal,omitempty"` // VND
	ItemCount  int32                  `protobuf:"varint,6,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	// When check_expected is set (DTM saga), the reservation must grant exactly
	// expected_discount (the pre-saga quote) — any drift (e.g. the voucher ran
	// out in between) aborts the branch so the saga rolls back.
	ExpectedDiscount int64 `protobuf:"varint,7,opt,name=expected_discount,json=expectedDiscount,proto3" json:"expected_discount,omitempty"`
	CheckExpected    bool  `protobuf:"varint,8,opt,name=check_expected,json=checkExpected,proto3" json:"check_expected,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApplyPromotionRequest) Reset() {
	*x = ApplyPromotionRequest{}
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPromotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPromotionRequest) ProtoMessage() {}

func (x *ApplyPromotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPromotionRequest.ProtoReflect.Descriptor instead.
func (*ApplyPromotionRequest) Descriptor() ([]byte, []int) {
	return file_proto_promotion_v1_promotion_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyPromotionRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ApplyPromotionRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ApplyPromotionRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ApplyPromotionRequest) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *ApplyPromotionRequest) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *ApplyPromotionRequest) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *ApplyPromotionRequest) GetExpectedDiscount() int64 {
	if x != nil {
		return x.ExpectedDiscount
	}
	return 0
}

func (x *ApplyPromotionRequest) GetCheckExpected() bool {
	if x != nil {
		return x.CheckExpected
	}
	return false
}

// AppliedCode carries the discount breakdown for a single promotion code.
type AppliedCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`      // ORDER_DISCOUNT | SHIP_DISCOUNT
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"` // VND discount applied
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppliedCode) Reset() {
	*x = AppliedCode{}
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppliedCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppliedCode) ProtoMessage() {}

func (x *AppliedCode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppliedCode.ProtoReflect.Descriptor instead.
func (*AppliedCode) Descriptor() ([]byte, []int) {
	return file_proto_promotion_v1_promotion_proto_rawDescGZIP(), []int{1}
}

func (x *AppliedCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AppliedCode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AppliedCode) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// ApplyPromotionResponse reports success/failure and the total discount breakdown.
type ApplyPromotionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ItemDiscount  int64                  `protobuf:"varint,2,opt,name=item_discount,json=itemDiscount,proto3" json:"item_discount,omitempty"` // total VND off item subtotal
	ShipDiscount  int64                  `protobuf:"varint,3,opt,name=ship_discount,json=shipDiscount,proto3" json:"ship_discount,omitempty"` // total VND off shipping
	Applied       []*AppliedCode         `protobuf:"bytes,4,rep,name=applied,proto3" json:"applied,omitempty"`
	ErrorReason   string                 `protobuf:"bytes,5,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"` // non-empty when success=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyPromotionResponse) Reset() {
	*x = ApplyPromotionResponse{}
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPromotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPromotionResponse) ProtoMessage() {}

func (x *ApplyPromotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPromotionResponse.ProtoReflect.Descriptor instead.
func (*ApplyPromotionResponse) Descriptor() ([]byte, []int) {
	return file_proto_promotion_v1_promotion_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyPromotionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyPromotionResponse) GetItemDiscount() int64 {
	if x != nil {
		return x.ItemDiscount
	}
	return 0
}

func (x *ApplyPromotionResponse) GetShipDiscount() int64 {
	if x != nil {
		return x.ShipDiscount
	}
	return 0
}

func (x *ApplyPromotionResponse) GetApplied() []*AppliedCode {
	if x != nil {
		return x.Applied
	}
	return nil
}

func (x *ApplyPromotionResponse) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

// QuotePromotionRequest asks for a dry-run discount computation. No reservation
// is created — the order service quotes the price before opening a saga, then the
// ApplyPromotion branch re-checks that the reserved discount matches the quote.
type QuotePromotionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Codes         []string               `protobuf:"bytes,3,rep,name=codes,proto3" json:"codes,omitempty"`
	Subtotal      int64                  `protobuf:"varint,4,opt,name=subtotal,proto3" json:"subtotal,omitempty"` // VND
	ItemCount     int32                  `protobuf:"varint,5,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotePromotionRequest) Reset() {
	*x = QuotePromotionRequest{}
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotePromotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotePromotionRequest) ProtoMessage() {}

func (x *QuotePromotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotePromotionRequest.ProtoReflect.Descriptor instead.
func (*QuotePromotionRequest) Descriptor() ([]byte, []int) {
	return file_proto_promotion_v1_promotion_proto_rawDescGZIP(), []int{3}
}

func (x *QuotePromotionRequest) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *QuotePromotionRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *QuotePromotionRequest) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *QuotePromotionRequest) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *QuotePromotionRequest) GetItemCount() int32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

type QuotePromotionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ItemDiscount  int64                  `protobuf:"varint,2,opt,name=item_discount,json=itemDiscount,proto3" json:"item_discount,omitempty"`
	ShipDiscount  int64                  `protobuf:"varint,3,opt,name=ship_discount,json=shipDiscount,proto3" json:"ship_discount,omitempty"`
	Applied       []*AppliedCode         `protobuf:"bytes,4,rep,name=applied,proto3" json:"applied,omitempty"`
	ErrorReason   string                 `protobuf:"bytes,5,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotePromotionResponse) Reset() {
	*x = QuotePromotionResponse{}
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotePromotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotePromotionResponse) ProtoMessage() {}

func (x *QuotePromotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotePromotionResponse.ProtoReflect.Descriptor instead.
func (*QuotePromotionResponse) Descriptor() ([]byte, []int) {
	return file_proto_promotion_v1_promotion_proto_rawDescGZIP(), []int{4}
}

func (x *QuotePromotionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *QuotePromotionResponse) GetItemDiscount() int64 {
	if x != nil {
		return x.ItemDiscount
	}
	return 0
}

func (x *QuotePromotionResponse) GetShipDiscount() int64 {
	if x != nil {
		return x.ShipDiscount
	}
	return 0
}

func (x *QuotePromotionResponse) GetApplied() []*AppliedCode {
	if x != nil {
		return x.Applied
	}
	return nil
}

func (x *QuotePromotionResponse) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

// ConfirmUsageRequest finalises RESERVED usages for an order (RESERVED→CONFIRMED).
type ConfirmUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUsageRequest) Reset() {
	*x = ConfirmUsageRequest{}
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUsageRequest) ProtoMessage() {}

func (x *ConfirmUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUsageRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUsageRequest) Descriptor() ([]byte, []int) {
	return file_proto_promotion_v1_promotion_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmUsageRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ConfirmUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUsageResponse) Reset() {
	*x = ConfirmUsageResponse{}
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUsageResponse) ProtoMessage() {}

func (x *ConfirmUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUsageResponse.ProtoReflect.Descriptor instead.
func (*ConfirmUsageResponse) Descriptor() ([]byte, []int) {
	return file_proto_promotion_v1_promotion_proto_rawDescGZIP(), []int{6}
}

func (x *ConfirmUsageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ReleaseUsageRequest voids RESERVED usages for an order and decrements used_count.
type ReleaseUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseUsageRequest) Reset() {
	*x = ReleaseUsageRequest{}
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseUsageRequest) ProtoMessage() {}

func (x *ReleaseUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseUsageRequest.ProtoReflect.Descriptor instead.
func (*ReleaseUsageRequest) Descriptor() ([]byte, []int) {
	return file_proto_promotion_v1_promotion_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseUsageRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ReleaseUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseUsageResponse) Reset() {
	*x = ReleaseUsageResponse{}
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseUsageResponse) ProtoMessage() {}

func (x *ReleaseUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_promotion_v1_promotion_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseUsageResponse.ProtoReflect.Descriptor instead.
func (*ReleaseUsageResponse) Descriptor() ([]byte, []int) {
	return file_proto_promotion_v1_promotion_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseUsageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_promotion_v1_promotion_proto protoreflect.FileDescriptor

const file_proto_promotion_v1_promotion_proto_rawDesc = "" +
	"\n" +
	"\"proto/promotion/v1/promotion.proto\x12\fpromotion.v1\"\x93\x02\n" +
	"\x15ApplyPromotionRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\tR\astoreId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05codes\x18\x04 \x03(\tR\x05codes\x12\x1a\n" +
	"\bsubtotal\x18\x05 \x01(\x03R\bsubtotal\x12\x1d\n" +
	"\n" +
	"item_count\x18\x06 \x01(\x05R\titemCount\x12+\n" +
	"\x11expected_discount\x18\a \x01(\x03R\x10expectedDiscount\x12%\n" +
	"\x0echeck_expected\x18\b \x01(\bR\rcheckExpected\"M\n" +
	"\vAppliedCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\xd4\x01\n" +
	"\x16ApplyPromotionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\ritem_discount\x18\x02 \x01(\x03R\fitemDiscount\x12#\n" +
	"\rship_discount\x18\x03 \x01(\x03R\fshipDiscount\x123\n" +
	"\aapplied\x18\x04 \x03(\v2\x19.promotion.v1.AppliedCodeR\aapplied\x12!\n" +
	"\ferror_reason\x18\x05 \x01(\tR\verrorReason\"\xa4\x01\n" +
	"\x15QuotePromotionRequest\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x14\n" +
	"\x05codes\x18\x03 \x03(\tR\x05codes\x12\x1a\n" +
	"\bsubtotal\x18\x04 \x01(\x03R\bsubtotal\x12\x1d\n" +
	"\n" +
	"item_count\x18\x05 \x01(\x05R\titemCount\"\xd4\x01\n" +
	"\x16QuotePromotionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\ritem_discount\x18\x02 \x01(\x03R\fitemDiscount\x12#\n" +
	"\rship_discount\x18\x03 \x01(\x03R\fshipDiscount\x123\n" +
	"\aapplied\x18\x04 \x03(\v2\x19.promotion.v1.AppliedCodeR\aapplied\x12!\n" +
	"\ferror_reason\x18\x05 \x01(\tR\verrorReason\"0\n" +
	"\x13ConfirmUsageRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"0\n" +
	"\x14ConfirmUsageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x13ReleaseUsageRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"0\n" +
	"\x14ReleaseUsageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xfa\x02\n" +
	"\x10PromotionService\x12[\n" +
	"\x0eApplyPromotion\x12#.promotion.v1.ApplyPromotionRequest\x1a$.promotion.v1.ApplyPromotionResponse\x12[\n" +
	"\x0eQuotePromotion\x12#.promotion.v1.QuotePromotionRequest\x1a$.promotion.v1.QuotePromotionResponse\x12U\n" +
	"\fConfirmUsage\x12!.promotion.v1.ConfirmUsageRequest\x1a\".promotion.v1.ConfirmUsageResponse\x12U\n" +
	"\fReleaseUsage\x12!.promotion.v1.ReleaseUsageRequest\x1a\".promotion.v1.ReleaseUsageResponseB(Z&project/proto/promotion/v1;promotionv1b\x06proto3"

var (
	file_proto_promotion_v1_promotion_proto_rawDescOnce sync.Once
	file_proto_promotion_v1_promotion_proto_rawDescData []byte
)

func file_proto_promotion_v1_promotion_proto_rawDescGZIP() []byte {
	file_proto_promotion_v1_promotion_proto_rawDescOnce.Do(func() {
		file_proto_promotion_v1_promotion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_promotion_v1_promotion_proto_rawDesc), len(file_proto_promotion_v1_promotion_proto_rawDesc)))
	})
	return file_proto_promotion_v1_promotion_proto_rawDescData
}

var file_proto_promotion_v1_promotion_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_promotion_v1_promotion_proto_goTypes = []any{
	(*ApplyPromotionRequest)(nil),  // 0: promotion.v1.ApplyPromotionRequest
	(*AppliedCode)(nil),            // 1: promotion.v1.AppliedCode
	(*ApplyPromotionResponse)(nil), // 2: promotion.v1.ApplyPromotionResponse
	(*QuotePromotionRequest)(nil),  // 3: promotion.v1.QuotePromotionRequest
	(*QuotePromotionResponse)(nil), // 4: promotion.v1.QuotePromotionResponse
	(*ConfirmUsageRequest)(nil),    // 5: promotion.v1.ConfirmUsageRequest
	(*ConfirmUsageResponse)(nil),   // 6: promotion.v1.ConfirmUsageResponse
	(*ReleaseUsageRequest)(nil),    // 7: promotion.v1.ReleaseUsageRequest
	(*ReleaseUsageResponse)(nil),   // 8: promotion.v1.ReleaseUsageResponse
}
var file_proto_promotion_v1_promotion_proto_depIdxs = []int32{
	1, // 0: promotion.v1.ApplyPromotionResponse.applied:type_name -> promotion.v1.AppliedCode
	1, // 1: promotion.v1.QuotePromotionResponse.applied:type_name -> promotion.v1.AppliedCode
	0, // 2: promotion.v1.PromotionService.ApplyPromotion:input_type -> promotion.v1.ApplyPromotionRequest
	3, // 3: promotion.v1.PromotionService.QuotePromotion:input_type -> promotion.v1.QuotePromotionRequest
	5, // 4: promotion.v1.PromotionService.ConfirmUsage:input_type -> promotion.v1.ConfirmUsageRequest
	7, // 5: promotion.v1.PromotionService.ReleaseUsage:input_type -> promotion.v1.ReleaseUsageRequest
	2, // 6: promotion.v1.PromotionService.ApplyPromotion:output_type -> promotion.v1.ApplyPromotionResponse
	4, // 7: promotion.v1.PromotionService.QuotePromotion:output_type -> promotion.v1.QuotePromotionResponse
	6, // 8: promotion.v1.PromotionService.ConfirmUsage:output_type -> promotion.v1.ConfirmUsageResponse
	8, // 9: promotion.v1.PromotionService.ReleaseUsage:output_type -> promotion.v1.ReleaseUsageResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_promotion_v1_promotion_proto_init() }
func file_proto_promotion_v1_promotion_proto_init() {
	if File_proto_promotion_v1_promotion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_promotion_v1_promotion_proto_rawDesc), len(file_proto_promotion_v1_promotion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_promotion_v1_promotion_proto_goTypes,
		DependencyIndexes: file_proto_promotion_v1_promotion_proto_depIdxs,
		MessageInfos:      file_proto_promotion_v1_promotion_proto_msgTypes,
	}.Build()
	File_proto_promotion_v1_promotion_proto = out.File
	file_proto_promotion_v1_promotion_proto_goTypes = nil
	file_proto_promotion_v1_promotion_proto_depIdxs = nil
}
