// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/promotion/v1/promotion.proto

package promotionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PromotionService_ApplyPromotion_FullMethodName = "/promotion.v1.PromotionService/ApplyPromotion"
	PromotionService_QuotePromotion_FullMethodName = "/promotion.v1.PromotionService/QuotePromotion"
	PromotionService_ConfirmUsage_FullMethodName   = "/promotion.v1.PromotionService/ConfirmUsage"
	PromotionService_ReleaseUsage_FullMethodName   = "/promotion.v1.PromotionService/ReleaseUsage"
)

// PromotionServiceClient is the client API for PromotionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PromotionServiceClient interface {
	// ApplyPromotion reserves one or more promotion codes for an order (idempotent
	// by order_id — re-sending returns the existing discount breakdown).
	ApplyPromotion(ctx context.Context, in *ApplyPromotionRequest, opts ...grpc.CallOption) (*ApplyPromotionResponse, error)
	// QuotePromotion computes the discount for a code set without reserving quota.
	QuotePromotion(ctx context.Context, in *QuotePromotionRequest, opts ...grpc.CallOption) (*QuotePromotionResponse, error)
	// ConfirmUsage transitions RESERVED usages to CONFIRMED once the order is placed.
	ConfirmUsage(ctx context.Context, in *ConfirmUsageRequest, opts ...grpc.CallOption) (*ConfirmUsageResponse, error)
	// ReleaseUsage voids RESERVED usages and returns the quota to the pool when an
	// order is cancelled or payment fails.
	ReleaseUsage(ctx context.Context, in *ReleaseUsageRequest, opts ...grpc.CallOption) (*ReleaseUsageResponse, error)
}

type promotionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPromotionServiceClient(cc grpc.ClientConnInterface) PromotionServiceClient {
	return &promotionServiceClient{cc}
}

func (c *promotionServiceClient) ApplyPromotion(ctx context.Context, in *ApplyPromotionRequest, opts ...grpc.CallOption) (*ApplyPromotionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyPromotionResponse)
	err := c.cc.Invoke(ctx, PromotionService_ApplyPromotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) QuotePromotion(ctx context.Context, in *QuotePromotionRequest, opts ...grpc.CallOption) (*QuotePromotionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuotePromotionResponse)
	err := c.cc.Invoke(ctx, PromotionService_QuotePromotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) ConfirmUsage(ctx context.Context, in *ConfirmUsageRequest, opts ...grpc.CallOption) (*ConfirmUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmUsageResponse)
	err := c.cc.Invoke(ctx, PromotionService_ConfirmUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promotionServiceClient) ReleaseUsage(ctx context.Context, in *ReleaseUsageRequest, opts ...grpc.CallOption) (*ReleaseUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseUsageResponse)
	err := c.cc.Invoke(ctx, PromotionService_ReleaseUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PromotionServiceServer is the server API for PromotionService service.
// All implementations must embed UnimplementedPromotionServiceServer
// for forward compatibility.
type PromotionServiceServer interface {
	// ApplyPromotion reserves one or more promotion codes for an order (idempotent
	// by order_id — re-sending returns the existing discount breakdown).
	ApplyPromotion(context.Context, *ApplyPromotionRequest) (*ApplyPromotionResponse, error)
	// QuotePromotion computes the discount for a code set without reserving quota.
	QuotePromotion(context.Context, *QuotePromotionRequest) (*QuotePromotionResponse, error)
	// ConfirmUsage transitions RESERVED usages to CONFIRMED once the order is placed.
	ConfirmUsage(context.Context, *ConfirmUsageRequest) (*ConfirmUsageResponse, error)
	// ReleaseUsage voids RESERVED usages and returns the quota to the pool when an
	// order is cancelled or payment fails.
	ReleaseUsage(context.Context, *ReleaseUsageRequest) (*ReleaseUsageResponse, error)
	mustEmbedUnimplementedPromotionServiceServer()
}

// UnimplementedPromotionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPromotionServiceServer struct{}

func (UnimplementedPromotionServiceServer) ApplyPromotion(context.Context, *ApplyPromotionRequest) (*ApplyPromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPromotion not implemented")
}
func (UnimplementedPromotionServiceServer) QuotePromotion(context.Context, *QuotePromotionRequest) (*QuotePromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuotePromotion not implemented")
}
func (UnimplementedPromotionServiceServer) ConfirmUsage(context.Context, *ConfirmUsageRequest) (*ConfirmUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmUsage not implemented")
}
func (UnimplementedPromotionServiceServer) ReleaseUsage(context.Context, *ReleaseUsageRequest) (*ReleaseUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseUsage not implemented")
}
func (UnimplementedPromotionServiceServer) mustEmbedUnimplementedPromotionServiceServer() {}
func (UnimplementedPromotionServiceServer) testEmbeddedByValue()                          {}

// UnsafePromotionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PromotionServiceServer will
// result in compilation errors.
type UnsafePromotionServiceServer interface {
	mustEmbedUnimplementedPromotionServiceServer()
}

func RegisterPromotionServiceServer(s grpc.ServiceRegistrar, srv PromotionServiceServer) {
	// If the following call pancis, it indicates UnimplementedPromotionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PromotionService_ServiceDesc, srv)
}

func _PromotionService_ApplyPromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).ApplyPromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_ApplyPromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).ApplyPromotion(ctx, req.(*ApplyPromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_QuotePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuotePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).QuotePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_QuotePromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).QuotePromotion(ctx, req.(*QuotePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_ConfirmUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).ConfirmUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_ConfirmUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).ConfirmUsage(ctx, req.(*ConfirmUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromotionService_ReleaseUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromotionServiceServer).ReleaseUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PromotionService_ReleaseUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromotionServiceServer).ReleaseUsage(ctx, req.(*ReleaseUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PromotionService_ServiceDesc is the grpc.ServiceDesc for PromotionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PromotionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "promotion.v1.PromotionService",
	HandlerType: (*PromotionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyPromotion",
			Handler:    _PromotionService_ApplyPromotion_Handler,
		},
		{
			MethodName: "QuotePromotion",
			Handler:    _PromotionService_QuotePromotion_Handler,
		},
		{
			MethodName: "ConfirmUsage",
			Handler:    _PromotionService_ConfirmUsage_Handler,
		},
		{
			MethodName: "ReleaseUsage",
			Handler:    _PromotionService_ReleaseUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/promotion/v1/promotion.proto",
}
